### ISSUE TITLE
Make a public/ folder

### ISSUE THREAD

**Issue by philsturgeon** [dracony/PHPixie2-preview#1]
Just to stop folks getting their sites hacked through bad configuration.

**Comment by dracony** [comment]
Well there is a /web folder that static files are url rewritten to. E.g  http://localhost/style.css can be stored in /web/style.css
.htaccess will restrict access to folders others than/ web, i havent modified it to do it yet though. It still protects old folder structure.

How do you like how modules are registered in the global container etc?
I wanted to use traits for that but dexided against it

**Comment by philsturgeon** [comment]
It should be the other way around. You point your vhost to one single folder so you don't rely on .htaccess for protection, as if your sysadmin accidentally disables allow override then all files and folders are web accessible.

**Comment by dracony** [comment]
Well you need to be the sysadmin to do vhost changes, so that situation will never really come up.
But if you are on a shared hosting you usually cannot put files outside of the root site folder, then having a mandatory subfolder can be very annoying.
On the other hand since the files are all php classes and the configs are just php fikes with arrays, executing them will not compromise anythings, just show an empty page.

**Comment by philsturgeon** [comment]
Sure, but it's common practice to do this just to avoid the situation coming up. Facebook figured it was impossible then started serving their PHP source code as text files.

Look at laravel, FuelPHP, silex, anything built in ruby, flask, Django, etc. People WILL request this.

**Comment by dracony** [comment]
Well since i'll be using composer now for the framework, i'll just make two application skeletons for both cases, or have a guide on how to do each setup.  So sure, thanks )

**Comment by philsturgeon** [comment]
No need, just make a public/ folder and have index.php in there. You don't need people reading your composer.json file either, as if they know the exact versions they know which patches you're not protected against.

**Comment by dracony** [comment]
What about shared hostings then?

**Comment by dracony** [comment]
How about i put index.php in both root folder and /web ?
This way it would work both ways  )

**Comment by philsturgeon** [comment]
Anything with CPanel, Plesk or webmin will allow a user to change that through the GUI, and that's 90% of the shared hosting population.

**Comment by philsturgeon** [comment]
Lol. Nope.

**Comment by dracony** [comment]
Well I'll trust you on that one then =)
,Haven't used a shared hosting since long ago, the one I had didnt allow that, but I do believe things have changed =)
